sudo: required

services:
    - docker

language: go

env:
  global:
    - TOOLS_CMD=golang.org/x/tools/cmd
    - PATH=$GOROOT/bin:$PATH

install:
 - go get ${TOOLS_CMD}/cover

script:
 - make test flannel-git

after_success:
  - if [ "$TRAVIS_BRANCH" = "flannel-git" ]; then
    make flannel-git;
    docker login -e="$QUAY_EMAIL" -u="$QUAY_USERNAME" -p="$QUAY_PASSWORD";
    docker push quay.io/coreos/flannel-git;
    fi

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then
    make flannel-git;
    docker login -u="$QUAY_USERNAME" -p="$QUAY_PASSWORD" quay.io;
    docker push quay.io/coreos/flannel-git;
    fi

notifications:
  email: false
